
name: Release Application

on:
  release:
    types: [created]

jobs:
  release:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # install yarn
      - name: Add yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
      # build
      - name: build and release
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build:for:github:ci
        env:
          GH_TOKEN: ${{ secrets.github_token }}
