
name: MacOS => Release Application

on:
 push:
  tags:
    - "v*"


jobs:
  release:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout Tag
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: v14.17.3
      - run: npm install yarn -g
      - run: yarn install

      # build
      - name: Build And Release
        run: yarn build:for:github:ci
        env:
          GH_TOKEN: ${{ secrets.github_token }}
